inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  CacheRootDirectory: tmp/
  TargetRubyVersion: 3.1

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/HashSyntax:
  Enabled: true
  EnforcedShorthandSyntax: either

RSpec/ExampleLength:
  Max: 50

RSpec/NestedGroups:
  Max: 4

Metrics/BlockLength:
  Max: 100
