name: VeracodeApiSigning
on:
  pull_request:
    branches-ignore:
      - 'gh-pages'
  push:
    branches-ignore:
      - 'gh-pages'
jobs:
  test:
    if: github.ref != 'refs/heads/main' or ${{ contains(github.event.head_commit.message, '#run-tests') }}
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        os: [ubuntu-latest, macos-latest]
        # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
        ruby: ['3.0', '3.1', '3.2.0-preview2', truffleruby]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: bundle exec rake

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Yard documents
        run: |
          bundle exec rake yard

      - name: Deploy pages
        if: github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: doc
          clean: true
          #clean-exclude: '[".gitattributes", ".gitignore", "CNAME", "LICENSE"]'
